server:
  port: 8083

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    reactor.netty: trace

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user
            - Method=POST,GET,DELETE
          filters:
            - SetPath=/api/user
        - id: user-id
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user/{id}
            - Method=GET,DELETE
          filters:
            - SetPath=/api/user/{id}
        - id: user-favouriteRecipes
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user/{id}/favouriteRecipes
            - Method=PATCH
          filters:
            - SetPath=/api/user/{id}/favouriteRecipes
        - id: ingredient
          uri: http://${INGREDIENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/ingredient
            - Method=POST,GET
          filters:
            - SetPath=/api/ingredient
        - id: ingredient-id
          uri: http://${INGREDIENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/ingredient/{id}
            - Method=GET,PUT,DELETE
          filters:
            - SetPath=/api/ingredient/{id}
        - id: recipe
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/recipe
            - Method=POST
          filters:
            - SetPath=/api/recipe
        - id: recipe-id
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/recipe/{id}
            - Method=GET,PUT,DELETE
          filters:
            - SetPath=/api/recipe/{id}
        - id: recipe-for-user
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/recipe/user/{userId}
            - Method=GET
          filters:
            - SetPath=/api/recipe/user/{userId}