apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mongo-user
            - name: DB_NAME
              value: userdb
            - name: DB_PORT
              value: "27017"
          image: r0881427/user-service
          name: user-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
