server:
  port: 8083

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    reactor.netty: trace

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user
            - Method=POST
          filters:
            - SetPath=/api/user
        - id: ingredient
          uri: http://${INGREDIENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/ingredient
            - Method=GET
          filters:
            - SetPath=/api/ingredient
        - id: recipe
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/recipe
            - Method=POST
          filters:
            - SetPath=/api/recipe
        - id: recipe-id
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/recipe/{id}
            - Method=GET,PUT,DELETE
          filters:
            - SetPath=/api/recipe/{id}
        - id: recipe-for-user-self
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/recipe/me
            - Method=GET
          filters:
            - SetPath=/api/recipe/me